name: Install Java 7 on Linux

on: 
  # push: 
    # branches-ignore: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update
    
    - name: Install Java 7
      run: |
         cd src/bin/java7
         tar -xvzf jre-7u80-linux-x64.tar.gz
         mv jre1.7.0_80 /opt/jre1.7.0_80

    - name: Setup Java 7 environment
      run: |
        echo "JAVA_HOME=/opt/jre1.7.0_80" >> $GITHUB_ENV
        echo "PATH=/opt/jre1.7.0_80/bin:$PATH" >> $GITHUB_ENV
    
    - name: Verify Java installation
      run: java -version

    - name: Download and install Ant 1.8.2
      run: |
        wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.8.2-bin.tar.gz
        tar -xzf apache-ant-1.8.2-bin.tar.gz
        sudo mv apache-ant-1.8.2 /opt/ant
        echo "ANT_HOME=/opt/ant" >> $GITHUB_ENV
        echo "PATH=/opt/ant/bin:$PATH" >> $GITHUB_ENV
  
    - name: Verify Ant installation
      run: ant -version

    # - name: Build with Ant
    #   run: ant compile

    # - name: Run tests
    #   run: ant run