name: Install Java 8 on Linux
on: 
  # push: 
    # branches-ignore: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update

    - name: Add repository for Java 8
      run: |
        sudo add-apt-repository ppa:openjdk-r/ppa
        sudo apt-get update

    - name: Install Java 8
      run: sudo apt-get install openjdk-8-jdk
    
    - name: Verify Java installation
      run: java -version

    - name: Download and install Ant 1.8.2
      run: |
        wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.8.2-bin.tar.gz
        tar -xzf apache-ant-1.8.2-bin.tar.gz
        sudo mv apache-ant-1.8.2 /opt/ant
        echo "ANT_HOME=/opt/ant" >> $GITHUB_ENV
        echo "PATH=/opt/ant/bin:$PATH" >> $GITHUB_ENV
  
    - name: Verify Ant installation
      run: ant -version

    - name: Build with Ant
      run: ant compile

    - name: Run tests
      run: ant run